#Caso esteja executando com o Autoscaling desabilitado, especifique o número de replicas
replicaCount: 1

image:
  tag: "${VERSION}"

service:
  #Para executar de forma local, altere o "type" para "NodePort"
  type: LoadBalancer
  port: 80
  cloud: aws

autoscaling:
  #Para habilitar o autoscaling, altere a variavel "enable" para "true" ("replicaCount" será ignorado)
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

#Configurações da instância RabbitMQ
rabbitmq_host: ${RABBITMQ_HOST}
rabbitmq_port: ${RABBITMQ_PORT}
rabbitmq_user: ${RABBITMQ_USER}
rabbitmq_password: ${RABBITMQ_PASSWORD}
rabbitmq_ssl: ${RABBITMQ_SSL}

#Request Manager
request_service_url: ${REQUEST_SERVICE_URL}

#User Manager
user_service_url: ${USER_SERVICE_URL}

#MailGun
mailgun_apikey: ${MAILGUN_APIKEY}