spring:
  application:
    name: notification-manager
  profiles:
    default: docker
  jackson:
    deserialization:
      fail-on-unknown-properties: true     
server:
  servlet:
    context-path: "/notification-manager/v1"
---
spring:
  config:
    activate:
      on-profile:
      - docker		
  request:
    serviceUrl: ${REQUEST_SERVICE_URL}
  user:
    serviceUrl: ${USER_SERVICE_URL}

  mailgun:
    apiKey: ${MAILGUN_APIKEY}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    ssl:
      enabled: ${RABBITMQ_SSL}