apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-manager-config
data:
  rabbitmq_host: {{ .Values.rabbitmq_host }}  
  rabbitmq_port: "{{ .Values.rabbitmq_port }}"
  rabbitmq_ssl: "{{ .Values.rabbitmq_ssl }}"
  request_service_url: "{{ .Values.request_service_url }}"
  user_service_url: "{{ .Values.user_service_url }}"  