apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-manager-deployment
  labels:
    vfc.fiapprj.perisatto.com/name: notification-manager
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      vfc.fiapprj.perisatto.com/name: notification-manager
  template:
    metadata:
      name: notification-manager-deployment
      labels:
        vfc.fiapprj.perisatto.com/name: notification-manager
    spec:
      containers:
        - name: notification-manager-service
          image: rperisatto/notification-manager:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-manager-config
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-manager-config
                  key: rabbitmq_port				 
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: notification-manager-secret
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-manager-secret
                  key: rabbitmq_password
            - name: RABBITMQ_SSL
              valueFrom:
                configMapKeyRef:
                  name: notification-manager-config
                  key: rabbitmq_ssl
            - name: REQUEST_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-manager-config
                  key: request_service_url
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-manager-config
                  key: user_service_url
            - name: MAILGUN_APIKEY
              valueFrom:
                secretKeyRef:
                  name: notification-manager-secret
                  key: mailgun_apikey
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /notification-manager/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /notification-manager/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
