name: deploy-pipeline
run-name: ${{ github.actor }} is running a new build.

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Service version wanted to deploy (a.k.a Image Tag)'

jobs:       
  Deploy-PRD:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: '${{secrets.AWS_ACCESS_KEY_ID}}'
      AWS_SECRET_ACCESS_KEY: '${{secrets.AWS_SECRET_ACCESS_KEY}}'	  
      AWS_SESSION_TOKEN: '${{secrets.AWS_SESSION_TOKEN}}'
      AWS_REGION: '${{ secrets.AWS_REGION }}'
      RABBITMQ_HOST: '${{secrets.RABBITMQ_HOST}}'
      RABBITMQ_PORT: '${{secrets.RABBITMQ_PORT}}'
      RABBITMQ_USER: '${{secrets.RABBITMQ_USER}}'
      RABBITMQ_PASSWORD: '${{secrets.RABBITMQ_PASSWORD}}'
      RABBITMQ_SSL: '${{secrets.RABBITMQ_SSL}}'	
      REQUEST_SERVICE_URL: '${{secrets.REQUEST_SERVICE_URL}}'	
      USER_SERVICE_URL: '${{secrets.USER_SERVICE_URL}}'
      MAILGUN_APIKEY: '${{secrets.MAILGUN_APIKEY}}'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name vfc-cluster --region ${{ secrets.AWS_REGION }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy to EKS using Helm
        env:
          VERSION: '${{github.event.inputs.version}}'
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}		
          helm upgrade --install $REPO_NAME --set image.tag=$VERSION --set request_service_url=$REQUEST_SERVICE_URL \
          --set user_service_url=$USER_SERVICE_URL --set mailgun_apikey=$MAILGUN_APIKEY --set rabbitmq_host=$RABBITMQ_HOST \
          --set rabbitmq_port=$RABBITMQ_PORT --set rabbitmq_user=$RABBITMQ_USER --set rabbitmq_password=$RABBITMQ_PASSWORD \
          --set rabbitmq_ssl=$RABBITMQ_SSL ./helm-chart